#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "going to lint-staged"

npx lint-staged

echo "lint-staged finished"

if ! npm run prettierCheck || ! npm run lintCheck
then
    npm run lintPrettier && npm run lintFix && echo "Please check the auto fix and commit again" && exit 1
else
    echo "pre commit success"
fi
